### ISSUE TITLE
Model mismatch problem

### ISSUE THREAD

**Issue by Wenboisstrong** [gm19900510/Pytorch_Retina_License_Plate#1]
Thanks for your work, I just want to test your model. I clone your repository and ran detect. But I got a model mismatch error. Here is the error message.
size mismatch for LandmarkHead.0.conv1x1.weight: copying a param with shape torch.Size ([20, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size ([16, 64, 1, 1]).
size mismatch for LandmarkHead.0.conv1x1.bias: copying a param with shape torch.Size ([20]) from checkpoint, the shape in current model is torch.Size ([16]).
size mismatch for LandmarkHead.1.conv1x1.weight: copying a param with shape torch.Size ([20, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size ([16, 64, 1, 1]).
size mismatch for LandmarkHead.1.conv1x1.bias: copying a param with shape torch.Size ([20]) from checkpoint, the shape in current model is torch.Size ([16]).
size mismatch for LandmarkHead.2.conv1x1.weight: copying a param with shape torch.Size ([20, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size ([16, 64, 1, 1]).
size mismatch for LandmarkHead.2.conv1x1.bias: copying a param with shape torch.Size ([20]) from checkpoint, the shape in current model is torch.Size ([16]).
Can you help me thank you

**Comment by Wenboisstrong** [comment]
I modified the parameters of this landmark conv by num_anchors * 8
———-> num_anchors * 10 But I'm curious why you modified it here

**Comment by gm19900510** [comment]
请 更新代码
