### ISSUE TITLE
train resnet50

### ISSUE THREAD

**Issue by lei522** [gm19900510/Pytorch_Retina_License_Plate#2]
when i train resnet50, i meet this error,
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    train()
  File "train.py", line 134, in train
    loss_l, loss_c, loss_landm = criterion(out, priors, targets)
  File "/home/neut/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/neut/workspace/Pytorch_Retina_License_Plate/layers/modules/multibox_loss.py", line 119, in forward
    loss_c = F.cross_entropy(conf_p, targets_weighted, reduction='sum')
  File "/home/neut/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 2009, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/neut/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 1838, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: invalid argument 2: non-empty vector or matrix expected at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:31

but mibilenet is ok, can you tell me how to solve it?

**Comment by gm19900510** [comment]
在traini.py文件中对照一下配置修正你的参数：

parser = argparse.ArgumentParser(description='RetinaLP Training')
parser.add_argument('--training_dataset', default='prepare_data/data_folder/train.txt', help='Training dataset directory')
parser.add_argument('--network', default='resnet50', help='Backbone network mobile0.25 or resnet50')
parser.add_argument('--num_workers', default=16, type=int, help='Number of workers used in dataloading')
parser.add_argument('--lr', '--learning-rate', default=1e-3, type=float, help='initial learning rate')
parser.add_argument('--momentum', default=0.9, type=float, help='momentum')
parser.add_argument('--resume_net', default=None, help='resume net for retraining')
parser.add_argument('--resume_epoch', default=0, type=int, help='resume iter for retraining')
parser.add_argument('--weight_decay', default=5e-4, type=float, help='Weight decay for SGD')
parser.add_argument('--gamma', default=0.1, type=float, help='Gamma update for SGD')
parser.add_argument('--save_folder', default='./weights/', help='Location to save checkpoint models')
