### ISSUE TITLE
关于数据集生成问题

### ISSUE THREAD

**Issue by SueeH** [gm19900510/Pytorch_Retina_License_Plate#6]
在数据集生成脚本中需要一个文件  './data_folder/data_list_CCPD_train.txt'
请问这个文件是怎么生成的？猜测文件每行保存一个图片的车牌信息。看代码每行信息应该是  img_path,label(0或者1)，num(车牌数量)，x,y,w,h
但是作者写的负样本生成代码中 给出的label都是 -1  但是长度是num = 3的情况？
请确认

**Comment by gm19900510** [comment]
cd Pytorch_Retina_License_Plate/prepare_data 
python reformat_CCPD.py 
python dataset_provider.py

**Comment by SueeH** [comment]
非常感谢及时回复。
另：在prior_box.py中，定义的anchor宽高都是min_size/image_size，因为image_size的都是640，所以anchor的宽高都是一样的？相当于是方框么？ 不知道我的理解是不是对呢？

**Comment by gm19900510** [comment]
是的，你可以改成矩形框，这样准确度会更好
